export interface GalleryImage {
  src: string;
  alt: string;
  title: string;
  caption: string;
  category: "ceramic-coating" | "ppf" | "detailing" | "interior" | "workshop";
  width: number;
  height: number;
  priority?: boolean;
}

const GEO = "Bolton, Greater Manchester";

export const GALLERY_IMAGES: GalleryImage[] = [
  {
    src: "/images/lamborghini-aventador-ceramic-coating-bolton.webp",
    alt: `Matte grey Lamborghini Aventador outside Latin King Detailing — ceramic coating specialists in ${GEO}`,
    title: `Lamborghini Aventador Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Lamborghini Aventador — matte ceramic coating. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 853,
    priority: true,
  },
  {
    src: "/images/ferrari-360-modena-detailing-bolton.webp",
    alt: `Silver-blue Ferrari 360 Modena outside Latin King Detailing workshop, Farnworth, ${GEO}`,
    title: `Ferrari 360 Modena Professional Detailing — Latin King Detailing, ${GEO}`,
    caption: "Ferrari 360 Modena — ceramic detail. Farnworth, Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
    priority: true,
  },
  {
    src: "/images/bentley-continental-gtc-ceramic-coating-bolton.webp",
    alt: `Black Bentley Continental GTC with Ceramic Pro 9H coating in our ${GEO} workshop`,
    title: `Bentley Continental GTC Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Bentley Continental GTC — Ceramic Pro 9H. Bolton workshop.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/bmw-m5-ceramic-coating-bolton-workshop.webp",
    alt: `Black BMW M5 receiving Ceramic Pro 9H coating at our workshop in ${GEO}`,
    title: `BMW M5 Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "BMW M5 — Ceramic Pro 9H application. Bolton.",
    category: "ceramic-coating",
    width: 720,
    height: 960,
  },
  {
    src: "/images/bmw-m5-f10-ceramic-coating-bolton.webp",
    alt: `Black BMW M5 F10 with mirror-gloss Ceramic Pro 9H ceramic coating at our ${GEO} workshop`,
    title: `BMW M5 F10 Mirror-Gloss Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "BMW M5 F10 — mirror-gloss Ceramic Pro 9H. Bolton.",
    category: "ceramic-coating",
    width: 720,
    height: 960,
  },
  {
    src: "/images/bmw-m5-ceramic-gloss-finish-bolton.webp",
    alt: `Black BMW M5 at night showing deep-gloss ceramic coating finish in ${GEO}`,
    title: `BMW M5 Deep-Gloss Ceramic Coating Result — ${GEO}`,
    caption: "BMW M5 — ceramic gloss finish. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/jaguar-fpace-ceramic-coating-bolton.webp",
    alt: `Blue Jaguar F-Pace ceramic coating treatment at Latin King Detailing, ${GEO}`,
    title: `Jaguar F-Pace Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Jaguar F-Pace — ceramic coating. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 853,
  },
  {
    src: "/images/porsche-macan-ceramic-coating-bolton.webp",
    alt: `Grey Porsche Macan ceramic coating at Latin King Detailing workshop, ${GEO}`,
    title: `Porsche Macan Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Porsche Macan — ceramic coating. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 853,
  },
  {
    src: "/images/seat-leon-cupra-ceramic-coating-bolton.webp",
    alt: `Orange SEAT Leon Cupra ceramic coating result at Latin King Detailing, ${GEO}`,
    title: `SEAT Leon Cupra Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "SEAT Leon Cupra — ceramic coating. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 853,
  },
  {
    src: "/images/bentley-continental-gt-ppf-installation-bolton.webp",
    alt: `Bentley Continental GT KAVACA paint protection film installation at Latin King Detailing, ${GEO}`,
    title: `Bentley Continental GT PPF Installation — Latin King Detailing, ${GEO}`,
    caption: "Bentley Continental GT — KAVACA PPF installation. Bolton.",
    category: "ppf",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/ceramic-coating-application-technician-bolton.webp",
    alt: `Certified technician applying Ceramic Pro 9H coating at our ${GEO} workshop`,
    title: `Ceramic Pro 9H Application by Certified Technician — Latin King Detailing, ${GEO}`,
    caption: "Certified technician — Ceramic Pro 9H application. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/paint-correction-ceramic-coating-bolton.webp",
    alt: `Professional paint correction before ceramic coating application at Latin King Detailing, ${GEO}`,
    title: `Paint Correction Before Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Paint correction — pre-coating preparation. Bolton.",
    category: "detailing",
    width: 720,
    height: 960,
  },
  {
    src: "/images/mirror-finish-ceramic-coating-reflection-bolton.webp",
    alt: `Ultra-gloss mirror finish achieved with Ceramic Pro 9H ceramic coating, ${GEO}`,
    title: `Ultra-Gloss Mirror Finish — Ceramic Pro 9H, ${GEO}`,
    caption: "Ultra-gloss mirror finish — Ceramic Pro 9H. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/luxury-car-detailing-ceramic-pro-bolton-workshop.webp",
    alt: `Luxury vehicles at Latin King Detailing, ${GEO} — ceramic coating and detailing specialists`,
    title: `Luxury Car Detailing — Latin King Detailing, ${GEO}`,
    caption: "Luxury detailing in progress. Latin King Detailing, Bolton.",
    category: "detailing",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/bmw-alloy-wheel-ceramic-coating-bolton.webp",
    alt: `BMW M-Sport alloy wheel with Ceramic Pro ceramic coating at our ${GEO} workshop`,
    title: `BMW Alloy Wheel Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "BMW M-Sport alloy — ceramic coated. Bolton.",
    category: "ceramic-coating",
    width: 720,
    height: 960,
  },
  {
    src: "/images/brake-caliper-coating-bolton.webp",
    alt: `Red brake caliper and wheel arch detail on vehicle at Latin King Detailing, ${GEO}`,
    title: `Brake Caliper Detail — Latin King Detailing, ${GEO}`,
    caption: "Brake caliper & arch detail. Bolton.",
    category: "detailing",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/leather-interior-protection-bolton.webp",
    alt: `Premium grey leather seat interior protection treatment at Latin King Detailing, ${GEO}`,
    title: `Leather Interior Protection — Latin King Detailing, ${GEO}`,
    caption: "Premium leather interior protection. Bolton.",
    category: "interior",
    width: 720,
    height: 960,
  },
  {
    src: "/images/ceramic-pro-north-west-workshop-farnworth-bolton.webp",
    alt: `Latin King Detailing workshop at night, 115 Albert Road, Farnworth, ${GEO}`,
    title: `Latin King Detailing Workshop — 115 Albert Road, Farnworth, ${GEO}`,
    caption: "Our workshop — 115 Albert Road, Farnworth, Bolton.",
    category: "workshop",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/ceramic-pro-north-west-detailing-studio-interior.webp",
    alt: `Professional detailing studio interior at Latin King Detailing, Farnworth, ${GEO}`,
    title: `Professional Detailing Studio — Latin King Detailing, Farnworth, ${GEO}`,
    caption: "Our professional detailing studio. Farnworth, Bolton.",
    category: "workshop",
    width: 1280,
    height: 720,
  },
  {
    src: "/images/motorcycle-ceramic-coating-bolton.webp",
    alt: `Ducati superbike ceramic coating protection at Latin King Detailing, ${GEO}`,
    title: `Motorcycle Ceramic Coating — Latin King Detailing, ${GEO}`,
    caption: "Ducati superbike — ceramic coating. Bolton.",
    category: "ceramic-coating",
    width: 1280,
    height: 720,
  },
];

export const GALLERY_CATEGORIES = [
  { key: "all", label: "All Work" },
  { key: "ceramic-coating", label: "Ceramic Coating" },
  { key: "ppf", label: "Paint Protection Film" },
  { key: "detailing", label: "Detailing" },
  { key: "interior", label: "Interior" },
  { key: "workshop", label: "Our Workshop" },
] as const;
